--- 
title: "Handbook of Graphs and Networks in People Analytics"
subtitle: "With Examples in R and Python"
author: "Keith McNulty"
site: bookdown::bookdown_site
always_allow_html: true
documentclass: krantz
bibliography: r/book.bib
fig-caption: yes
link-citations: yes
github-repo: keithmcnulty/ona_book
pagetitle: "Handbook of Graphs and Networks in People Analytics"
description:  "A technical manual of graphs, networks and their applications in the people and social sciences"
url:  "https://ona-book.org"
twitter-handle: "dr_keithmcnulty"
---


```{r, echo = FALSE}
library(reticulate)
library(colorBlindness)
options(ggplot2.discrete.fill = Blue2DarkRed18Steps)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)

if (knitr::is_latex_output()) {
  options(width = 100)
}

# set this next variable to false to avoid evaluating computationally heavy chunks
eval_heavy_chunks <- FALSE

# knitr::opts_chunk$set(dpi=300)

# bookdown::render_book("index.Rmd", output_format = "bookdown::bs4_book", config_file = "_bookdown_bs4.yml")
# bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", config_file = "_bookdown_pdf.yml")
# bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", config_file = "_bookdown_gitbook.yml")
```

# Introduction {-}


```{r}
## placeholder
```

