<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>7 Vertex Importance and Centrality | Handbook of Graphs and Networks in People Analytics</title>
<meta name="author" content="Keith McNulty">
<meta name="description" content="It follows from much of the earlier work we have been doing in this book that the vertices of a graph can provide rich information about a network, its structure and its dynamics. In sociology and...">
<meta name="generator" content="bookdown 0.22.15 with bs4_book()">
<meta property="og:title" content="7 Vertex Importance and Centrality | Handbook of Graphs and Networks in People Analytics">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ona-book.org/vertex-importance.html">
<meta property="og:image" content="https://ona-book.org/www/cover/cover-ona.png">
<meta property="og:description" content="It follows from much of the earlier work we have been doing in this book that the vertices of a graph can provide rich information about a network, its structure and its dynamics. In sociology and...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="7 Vertex Importance and Centrality | Handbook of Graphs and Networks in People Analytics">
<meta name="twitter:site" content="@dr_keithmcnulty">
<meta name="twitter:description" content="It follows from much of the earlier work we have been doing in this book that the vertices of a graph can provide rich information about a network, its structure and its dynamics. In sociology and...">
<meta name="twitter:image" content="https://ona-book.org/www/cover/cover-ona.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9.5/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="libs/vis-4.20.1/vis.css" rel="stylesheet">
<script src="libs/vis-4.20.1/vis.min.js"></script><script src="libs/visNetwork-binding-2.0.9/visNetwork.js"></script><script src="libs/d3-4.5.0/d3.min.js"></script><script src="libs/forceNetwork-binding-0.4/forceNetwork.js"></script><script src="libs/sankey-1/sankey.js"></script><script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="css/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="With Examples in R and Python">Handbook of Graphs and Networks in People Analytics</a>:
        <small class="text-muted">With Examples in R and Python</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li><a class="" href="introduction.html">Introduction</a></li>
<li><a class="" href="everywhere.html"><span class="header-section-number">1</span> Graphs everywhere!</a></li>
<li><a class="" href="r-intro.html"><span class="header-section-number">2</span> The Basics of the R Programming Language</a></li>
<li><a class="" href="working.html"><span class="header-section-number">3</span> Working With Graphs</a></li>
<li><a class="" href="viz-graphs.html"><span class="header-section-number">4</span> Visualizing Graphs</a></li>
<li><a class="" href="restructuring-data.html"><span class="header-section-number">5</span> Restructuring Data For Use in Graphs</a></li>
<li><a class="" href="paths-distance.html"><span class="header-section-number">6</span> Paths and Distance</a></li>
<li><a class="active" href="vertex-importance.html"><span class="header-section-number">7</span> Vertex Importance and Centrality</a></li>
<li><a class="" href="community.html"><span class="header-section-number">8</span> Components, Communities and Cliques</a></li>
<li><a class="" href="similarity.html"><span class="header-section-number">9</span> Assortativity and Comparability of Networks</a></li>
<li><a class="" href="databases.html"><span class="header-section-number">10</span> Graphs as Databases</a></li>
<li><a class="" href="advanced-viz.html"><span class="header-section-number">11</span> Advanced Network Visualization</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/keithmcnulty/ona_book">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="vertex-importance" class="section level1" number="7">
<h1>
<span class="header-section-number">7</span> Vertex Importance and Centrality<a class="anchor" aria-label="anchor" href="#vertex-importance"><i class="fas fa-link"></i></a>
</h1>
<p>It follows from much of the earlier work we have been doing in this book that the vertices of a graph can provide rich information about a network, its structure and its dynamics. In sociology and psychology contexts, this is particularly true, because more often than not vertices represent people. The fact that people play different roles and have different influences inside groups and communities has motivated centuries of sociological and psychological research, so it is unsurprising that the concept of vertex importance and influence is of great interest in the study of people or organizational networks.</p>
<p>But importance and influence are not precisely defined concepts, and to make them real within the context of graphs and networks we need to find some sort of mathematical definition for them. In many visual graph layouts, more important or influential vertices that have a stronger roles in overall connectivity will usually be positioned towards the center of a group of other vertices<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;If you want to see an earlier example of this, take a look at Figure &lt;a href="viz-graphs.html#fig:fr-karate"&gt;4.8&lt;/a&gt; for Zachary’s Karate Club network and note the positions of the influential actors Mr Hi and John A.&lt;/p&gt;'><sup>40</sup></a>. Intuitively therefore, we use the term ‘centrality’ to describe the importance or influence of a vertex in the connected structure of a graph.</p>
<p>In this chapter we will go through the most common types of centrality that can be measured for vertices in graphs, and discuss how they can be interpreted in the context of people or organizational networks. We will show how to calculate different types of centrality in R or Python and how to illustrate centrality in graph visualizations. We will then reprise our example of the French office building network from the previous chapter to illustrate the utility of centrality in network analysis.</p>
<p>In this chapter we will use the <span class="math inline">\(G_{14}\)</span> graph which we introduced in the previous chapter, which is an undirected and unweighted graph. Most centrality measures are valid and easily calculated for directed graphs, and will depend on defining the direction of the edges to consider. Figure <a href="vertex-importance.html#fig:g14-colored">7.1</a> shows the <span class="math inline">\(G_{14}\)</span> graph with four vertices of interest colored differently from other vertices.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:g14-colored"></span>
<img src="_main_files/figure-html/g14-colored-1.png" alt="The $G_{14}$ graph with four vertices of interest colored differently" width="672"><p class="caption">
Figure 7.1: The <span class="math inline">\(G_{14}\)</span> graph with four vertices of interest colored differently
</p>
</div>
<div id="vertex-centrality-measures-in-graphs" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> Vertex centrality measures in graphs<a class="anchor" aria-label="anchor" href="#vertex-centrality-measures-in-graphs"><i class="fas fa-link"></i></a>
</h2>
<p>As we look at the <span class="math inline">\(G_{14}\)</span> graph in Figure <a href="vertex-importance.html#fig:g14-colored">7.1</a>, we see the colored nodes seem to occupy prominent roles in the connective structure of the graph. If we removed Vertex 9, for example, we would split our graph into two sizeable disconnected components. Vertex 4 seems to be connected to a lot of immediate neighbours, and we would also split the graph if we removed it, leaving behind some isolates<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Recall that isolates are vertices that are not connected to any other vertices.&lt;/p&gt;"><sup>41</sup></a>. Vertex 7 seems to occupy a stealthy position from which to efficiently reach other nodes, while Vertex 8 seems to sit in between those other three and probably can’t be ignored for that reason alone.</p>
<p>What if these vertices represented people in an organization? Would the departure of Vertex 4 mean that Vertices 1, 2, 3 and 5 lose their entire connection to the remainder of the organization? Would the departure of Vertex 9 split the organization in two in terms of the flow of work? If we wanted to distribute important information across the organization by means of these connections, which vertex would be a good place to start? By understanding centrality we can start to appreciate the possible impact of changes to the network, or identify important or influential actors in the network.</p>
<div id="degree-centrality" class="section level3" number="7.1.1">
<h3>
<span class="header-section-number">7.1.1</span> Degree centrality<a class="anchor" aria-label="anchor" href="#degree-centrality"><i class="fas fa-link"></i></a>
</h3>
<p>The <strong>degree centrality</strong> or <strong>valence</strong> of a vertex <span class="math inline">\(v\)</span> is the number of edges connected to <span class="math inline">\(v\)</span>. Alternatively stated, in an unweighted graph it is the number of neighbors of <span class="math inline">\(v\)</span> or the number of vertices of distance 1 from <span class="math inline">\(v\)</span>. For example, the degree centrality of Vertex 8 in <span class="math inline">\(G_{14}\)</span> is 3, and for Vertex 4 it is 7. It should not be difficult to see that Vertex 4 has the highest degree centrality in <span class="math inline">\(G_{14}\)</span>.</p>
<p>Degree centrality is a measure of immediate connection in a network. It could be interpreted as immediate reach in a social network. Its precise interpretation depends strongly on the nature of the connection. In a network of academic co-authoring, someone with high degree centrality has collaborated directly with a larger number of other academics. In our French office building network from Section <a href="paths-distance.html#illustrative-6">6.3</a>, someone of high degree centrality is likely to be well-known socially to a greater number of colleagues.</p>
<p>Related to degree centrality is <em>ego size</em>. The <span class="math inline">\(n\)</span>-th degree ego network of a given vertex <span class="math inline">\(v\)</span> is a set including <span class="math inline">\(v\)</span> itself and all vertices of distance at most <span class="math inline">\(n\)</span> from <span class="math inline">\(v\)</span>. The <span class="math inline">\(n\)</span>-th degree ego size is the number of vertices in the <span class="math inline">\(n\)</span>-th degree ego network. In <span class="math inline">\(G_{14}\)</span>, Vertex 8 has a 1st degree ego size of 4, a 2nd degree ego size of 11, and third degree ego size of 14 (the entire graph). It easily follows that the 1st-degree ego size of a vertex is one greater than the degree centrality of the vertex.</p>
</div>
<div id="closeness-centrality" class="section level3" number="7.1.2">
<h3>
<span class="header-section-number">7.1.2</span> Closeness centrality<a class="anchor" aria-label="anchor" href="#closeness-centrality"><i class="fas fa-link"></i></a>
</h3>
<p>The <strong>closeness centrality</strong> of a vertex <span class="math inline">\(v\)</span> in a connected graph is the inverse of the sum of the distances from <span class="math inline">\(v\)</span> to all other vertices. Let’s take a moment to understand this better by looking at an example: we will calculate the closeness centrality of Vertex 8 from <span class="math inline">\(G_{14}\)</span>. Vertex 8 has the following distances to other vertices:</p>
<ul>
<li>Distance 1 to vertices 4, 7 and 9</li>
<li>Distance 2 to vertices 1, 2, 3, 5, 6, 10 and 13</li>
<li>Distance 3 to vertices 11, 12 and 14</li>
</ul>
<p>The sum of these distances is 26, and the inverse of 26 is 0.038. Inverting this distance means that lower total distances will generate higher closeness centrality. Therefore the vertex with the highest closeness centrality will be the most efficient in reaching all the other vertices in the graph. While Vertex 8 has one of the highest closeness centralities in <span class="math inline">\(G_{14}\)</span>, Vertex 7 has a slightly higher closeness centrality, because its additional direct edge to Vertex 6 gives it a slightly smaller total distance of 25 to the other vertices, and therefore a slightly higher closeness centrality of 0.04.</p>
<p>Closeness centrality is a measure of how efficiently the entire graph can be traversed from a given vertex. This is particularly valuable in the study of information flow. In social networks, information shared by those with high closeness centrality will likely reach the entire network more efficiently. In our French office building network from Section <a href="paths-distance.html#illustrative-6">6.3</a>, those with high closeness centrality may be better choices for efficiently spreading a message through social interactions/word-of-mouth.</p>
</div>
<div id="betweenness-centrality" class="section level3" number="7.1.3">
<h3>
<span class="header-section-number">7.1.3</span> Betweenness centrality<a class="anchor" aria-label="anchor" href="#betweenness-centrality"><i class="fas fa-link"></i></a>
</h3>
<p>The <strong>betweenness centrality</strong> of a vertex <span class="math inline">\(v\)</span> is calculated by taking each pair of other vertices <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, calculating the number of shortest paths between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> that go through <span class="math inline">\(v\)</span>, dividing by the total number of shortest paths between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, then summing over all such pairs of vertices in the graph. We can use the following process to manually calculate this for Vertex 8 in <span class="math inline">\(G_{14}\)</span>:</p>
<ul>
<li>If we look at all pairs of vertices 9 thru 14, we conclude that 8 is not on any shortest paths between these vertices (betweenness centrality: 0).</li>
<li>Similarly for vertices 1 thru 7 we conclude that Vertex 8 is not on any of these shortest paths either (betweenness centrality: 0).</li>
<li>Now we look at all pairs between Vertex 7 and vertices 9 thru 14, and conclude that 8 is not on any shortest paths for these pairs because vertices 7 and 9 are adjacent (betweenness centrality: 0).</li>
<li>Now we look at all pairs betwee Vertex 6 and Vertices 9 thru 14, and conclude that 8 is not on any of these shortest paths, because a shorter route is through Vertex 7 (betweenness centrality: 0).</li>
<li>Finally, we look at all pairs between Vertices 1 thru 5 and Vertices 9 thru 14, and conclude that for each of the 30 such pairs there are two shortest paths, one of which goes through Vertex 7 and the other through Vertex 8 (betweenness centrality: <span class="math inline">\(0.5 \times 30 = 15\)</span>).<br>
</li>
<li>Summing over these, we conclude that the betweenness centrality of Vertex 8 in <span class="math inline">\(G_{14}\)</span> is 15.</li>
</ul>
<p>Using similar logic it is not too difficult to reason that Vertex 9 has the highest betweenness centrality in <span class="math inline">\(G_{14}\)</span>. If we split the graph on either side of Vertex 9, we have betweenness centralities of zero in the sets of vertices on either side, but any path between vertices on either side of Vertex 9 <em>must</em> pass through Vertex 9. There are 46 such paths between Vertices 1 thru 8 and Vertices 10 thru 14, and so the total betweenness centrality of Vertex 9 is 46.</p>
<p>Betweenness centrality is a measure of how important a given vertex is in connecting other pairs of vertices in the graph. It makes intuitive sense that Vertex 9 should have the highest betweenness centrality because its removal would have the largest destructive effect on overall connectivity in <span class="math inline">\(G_{14}\)</span>, splitting it into a disconnected graph with two sizeable connected components. In people networks, individuals with higher betweenness centrality can be regarded as playing important roles in the ensuring overall connectivity of the network, and if they are removed from the network the risks of overall disconnection are higher. This has strong applications in studying the effects of attrition and departures from organizations.</p>
<div class="thinkahead">
<p><strong>Playing around:</strong> It’s worth thinking about some of the things we did in the previous chapter based on our new understanding of degree, closeness and betweenness centrality. For example, how do certain types of central vertices influence the overall ‘closeness’ of a network? What would happen to average distance or edge density if we remove certain central vertices? Try playing around with removing Vertices 4 (highest degree centrality), 7 (highest closeness centrality) and 9 (highest betweenness centrality) from <span class="math inline">\(G_{14}\)</span> and determining the impact of these removals on diameter, mean distance and density.</p>
</div>
</div>
<div id="eigenvector-centrality" class="section level3" number="7.1.4">
<h3>
<span class="header-section-number">7.1.4</span> Eigenvector centrality<a class="anchor" aria-label="anchor" href="#eigenvector-centrality"><i class="fas fa-link"></i></a>
</h3>
<p>The <strong>Eigenvector centrality</strong> or <strong>relative centrality</strong> or <strong>prestige</strong> of a vertex is a measure of how connected the vertex is to other influential vertices. It is impossible to define this without a little linear algebra.</p>
<p>Recall from Section <a href="working.html#rep-graphs">3.1.4</a> that the adjacency matrix <span class="math inline">\(A = (a_{ij})\)</span> for an unweighted graph <span class="math inline">\(G\)</span> containing <span class="math inline">\(p\)</span> vertices is defined as <span class="math inline">\(a_{ij} = 1\)</span> if <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> are adjacent vertices in <span class="math inline">\(G\)</span> and 0 otherwise. A vector <span class="math inline">\(x = (x_1, x_2, ...,x_p)\)</span> and scalar value <span class="math inline">\(\lambda\)</span> are considered an eigenvector and eigenvalue of <span class="math inline">\(A\)</span> if they satisfy the equation</p>
<p><span class="math display">\[
Ax = \lambda{x}
\]</span>
If we require that <span class="math inline">\(x\)</span> can only have positive entries, then a unique solution exists to this equation which has maximum eigenvalue <span class="math inline">\(\lambda\)</span>. We take <span class="math inline">\(x\)</span> and <span class="math inline">\(\lambda\)</span> for this solution and define the eigenvector centrality for vertex <span class="math inline">\(v\)</span> as</p>
<p><span class="math display">\[
\frac{1}{\lambda}\sum_{w \in G}a_{vw}x_w
\]</span></p>
<p>Because this is solving for a system of linear equations with coefficients that relate to the connectedness of neighbouring vertices, its solution is a measure of the relative influence of a vertex as a function of the influences of the vertices it is connected to. Vertices can have high influence through being connected to a lot of other vertices with low influence, or through being connected to a small number of highly influential vertices. Vertex 10 in <span class="math inline">\(G_{14}\)</span> has an eigenvector centrality of 0.12, and Vertex 2 has an eigenvector centrality of 0.23. This makes sense because Vertex 2 is connected to Vertex 4, which we already know has the highest degree centrality in the network. Intuitively, it shouldn’t be too hard to appreciate that Vertex 4 as the highest eigenvector centrality in <span class="math inline">\(G_{14}\)</span>.</p>
<p>In directed graphs, eigenvector centrality gives rise to interesting measures of different types of influence. For example, imagine a citation network where certain authors are regularly citing a lot of influential articles. These authors are known as <em>hubs</em>, and their <em>outgoing</em> eigenvector centrality will be high. <em>Hub centrality</em> is the outgoing eigenvector centrality of a vertex. Meanwhile, authors who have high incoming eigenvector centrality will be frequently referenced by hubs, and these authors are known as <em>authorities</em>. <em>Authority centrality</em> is the <em>incoming</em> eigenvector centrality of a vertex. These types of measures are becoming increasingly adopted in fields such as bibliometrics. Note that in undirected graphs the hub score, authority score and eigenvector centrality of vertices are identical.</p>
<div class="thinkahead">
<p><strong>Playing around:</strong> We have not looked at the impact of edge weights on centrality in this chapter. This is because it is unusual to consider edge weights in centrality measures. Nonetheless, most centrality measures do have approaches to consider edge weights, and this is a topic of ongoing research. Usually in these situations, edge weights are transformed to be cost functions — for example by inverting them — so that edges with higher weights are considered ‘preferable’ in graph traversal. To see what I mean, go back and have a look at the <span class="math inline">\(G_{14W}\)</span> weighted graph from the previous chapter. Pick pairs of vertices and see what the shortest path between them would be using the sum of weights of edges, and what it would be using the sum of the inverse weights of edges.</p>
</div>
</div>
</div>
<div id="calculating-and-illustrating-vertex-centrality" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Calculating and illustrating vertex centrality<a class="anchor" aria-label="anchor" href="#calculating-and-illustrating-vertex-centrality"><i class="fas fa-link"></i></a>
</h2>
<div id="calculating-in-r-1" class="section level3" number="7.2.1">
<h3>
<span class="header-section-number">7.2.1</span> Calculating in R<a class="anchor" aria-label="anchor" href="#calculating-in-r-1"><i class="fas fa-link"></i></a>
</h3>
<p>Degree centrality can be calculated for a specific set of vertices using the <code><a href="https://rdrr.io/pkg/igraph/man/degree.html">degree()</a></code> function in <code>igraph</code>. By default, the degree centrality will be calculated for all vertices. Let’s load up our <span class="math inline">\(G_{14}\)</span> graph to demonstrate as we did in the previous chapter.</p>
<div class="sourceCode" id="cb379"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://igraph.org">igraph</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>

<span class="co"># get g14 edgelist and ignore weights</span>
<span class="va">g14_edgelist</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"https://ona-book.org/data/g14_edgelist.csv"</span><span class="op">)</span>
<span class="va">g14_unweighted</span> <span class="op">&lt;-</span> <span class="va">g14_edgelist</span> |&gt; 
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">weight</span><span class="op">)</span>

<span class="co"># create graph</span>
<span class="va">g14</span> <span class="op">&lt;-</span> <span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/graph_from_data_frame.html">graph_from_data_frame</a></span><span class="op">(</span><span class="va">g14_unweighted</span>, directed <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="co"># calculate degree centrality for all vertices</span>
<span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/degree.html">degree</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span></code></pre></div>
<pre><code>##  9 10 11 13  8  4  6  1 12 14  7  2  3  5 
##  4  3  2  2  3  7  2  2  2  1  4  2  1  1</code></pre>
<p>We can see that Vertex 4 has a degree centrality of 7, which agrees with our earlier manual calculations. Ego networks and ego sizes can be determined using the <code><a href="https://rdrr.io/pkg/igraph/man/ego.html">ego()</a></code> and <code><a href="https://rdrr.io/pkg/igraph/man/ego.html">ego_size()</a></code> functions.</p>
<div class="sourceCode" id="cb381"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># 2nd order ego network of Vertex 4</span>
<span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/ego.html">ego</a></span><span class="op">(</span><span class="va">g14</span>, order <span class="op">=</span> <span class="fl">2</span>, nodes <span class="op">=</span> <span class="st">"4"</span><span class="op">)</span></code></pre></div>
<pre><code>## [[1]]
## + 9/14 vertices, named, from caab14c:
## [1] 4 8 6 1 7 2 3 5 9</code></pre>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># size of ego network</span>
<span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/ego.html">ego_size</a></span><span class="op">(</span><span class="va">g14</span>, order <span class="op">=</span> <span class="fl">2</span>, nodes <span class="op">=</span> <span class="st">"4"</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Closeness centrality is calculated using the <code><a href="https://rdrr.io/pkg/igraph/man/closeness.html">closeness()</a></code> function for all or a subset of vertices. Let’s verify that this function returns the same results for Vertices 7 and 8 that we manually calculated earlier.</p>
<div class="sourceCode" id="cb385"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/closeness.html">closeness</a></span><span class="op">(</span><span class="va">g14</span>, vids <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"7"</span>, <span class="st">"8"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##          7          8 
## 0.04000000 0.03846154</code></pre>
<p>Betweenness centrality is calculated using the <code><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness()</a></code> function in a similar way. Let’s verify our previous manual calculations for Vertices 8 and 9.</p>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="va">g14</span>, v <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"8"</span>, <span class="st">"9"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##  8  9 
## 15 46</code></pre>
<p>Finally, eigenvector centrality can be calculated using the <code><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality()</a></code> function. Note that this returns a list including various details about the computation<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;For example if you are curious to know the eigenvalue, you can look at the &lt;code&gt;value&lt;/code&gt; element of the list&lt;/p&gt;"><sup>42</sup></a>. To see the actual centralities, you should call the <code>vector</code> element of the output list. Note also that this function scales the values by default so that the maximum eigenvector centrality is 1. To avoid this, set <code>scale = FALSE</code>.</p>
<div class="sourceCode" id="cb389"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">eigens</span> <span class="op">&lt;-</span> <span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality</a></span><span class="op">(</span><span class="va">g14</span>, scale <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">eigens</span><span class="op">$</span><span class="va">vector</span></code></pre></div>
<pre><code>##          9         10         11         13          8          4          6          1         12         14          7 
## 0.30157876 0.11585270 0.04773223 0.09618665 0.37800315 0.55038069 0.29000589 0.22676118 0.04773223 0.02806617 0.44350955 
##          2          3          5 
## 0.22676118 0.16059484 0.16059484</code></pre>
<p>We can see confirmation here that Vertex 4 has the highest eigenvector centrality.</p>
<div class="thinkahead">
<p><strong>Playing around:</strong> There are a few other centrality-like measures available in <code>igraph</code> which you could explore and try to understand. Examples include <code><a href="https://rdrr.io/pkg/igraph/man/page_rank.html">page_rank()</a></code> for Google’s measure of importance of a web page, and <code><a href="https://rdrr.io/pkg/igraph/man/hub_score.html">hub_score()</a></code> and <code><a href="https://rdrr.io/pkg/igraph/man/authority_score.html">authority_score()</a></code> for directed networks. Consider testing these out on some datasets, like the <code>wikivote</code> data set from the <code>onadata</code> package or downloaded from the internet<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://ona-book.org/data/wikivote.csv" class="uri"&gt;https://ona-book.org/data/wikivote.csv&lt;/a&gt;&lt;/p&gt;'><sup>43</sup></a>.</p>
</div>
</div>
<div id="calculating-in-python-1" class="section level3" number="7.2.2">
<h3>
<span class="header-section-number">7.2.2</span> Calculating in Python<a class="anchor" aria-label="anchor" href="#calculating-in-python-1"><i class="fas fa-link"></i></a>
</h3>
<p>Again, as in the work in the previous chapter, centrality function in <code>networkx</code> are very similar to those in <code>igraph</code>. The <code><a href="https://rdrr.io/pkg/igraph/man/degree.html">degree()</a></code> function calculates degree centrality for all vertices by default, or you can specify a list of vertices.</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb391-1"><a href="vertex-importance.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb391-2"><a href="vertex-importance.html#cb391-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb391-3"><a href="vertex-importance.html#cb391-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb391-4"><a href="vertex-importance.html#cb391-4" aria-hidden="true" tabindex="-1"></a><span class="co"># download edgelist and remove weights</span></span>
<span id="cb391-5"><a href="vertex-importance.html#cb391-5" aria-hidden="true" tabindex="-1"></a>g14_edgelist <span class="op">=</span> pd.read_csv(<span class="st">"https://ona-book.org/data/g14_edgelist.csv"</span>)</span>
<span id="cb391-6"><a href="vertex-importance.html#cb391-6" aria-hidden="true" tabindex="-1"></a>g14_undirected <span class="op">=</span> g14_edgelist.drop(<span class="st">'weight'</span>, axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb391-7"><a href="vertex-importance.html#cb391-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb391-8"><a href="vertex-importance.html#cb391-8" aria-hidden="true" tabindex="-1"></a><span class="co"># create undirected g14 graph</span></span>
<span id="cb391-9"><a href="vertex-importance.html#cb391-9" aria-hidden="true" tabindex="-1"></a>g14 <span class="op">=</span> nx.from_pandas_edgelist(g14_undirected, source <span class="op">=</span> <span class="st">'from'</span>, target <span class="op">=</span> <span class="st">'to'</span>)</span>
<span id="cb391-10"><a href="vertex-importance.html#cb391-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb391-11"><a href="vertex-importance.html#cb391-11" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate degree centrality of Vertex 4</span></span>
<span id="cb391-12"><a href="vertex-importance.html#cb391-12" aria-hidden="true" tabindex="-1"></a>nx.degree(g14, [<span class="dv">4</span>, <span class="dv">9</span>])</span></code></pre></div>
<pre><code>## DegreeView({4: 7, 9: 4})</code></pre>
<p>There are also methods called <code><a href="https://rdrr.io/pkg/igraph/man/degree.html">degree()</a></code> for a <code>Graph()</code> object as well as <code>in_degree()</code> and <code>out_degree()</code> for <code>DiGraph()</code> objects in <code>networkx</code>.</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb393-1"><a href="vertex-importance.html#cb393-1" aria-hidden="true" tabindex="-1"></a>g14.degree(<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## 7</code></pre>
<p>The ego network of a vertex can be obtained using <code><a href="https://rdrr.io/pkg/igraph/man/ego.html">ego_graph()</a></code> function. To obtain the 2nd order ego network of Node 4:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb395-1"><a href="vertex-importance.html#cb395-1" aria-hidden="true" tabindex="-1"></a>ego_4_2 <span class="op">=</span> nx.ego_graph(g14, n <span class="op">=</span> <span class="dv">4</span>, radius <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb395-2"><a href="vertex-importance.html#cb395-2" aria-hidden="true" tabindex="-1"></a>ego_4_2.nodes</span></code></pre></div>
<pre><code>## NodeView((9, 8, 7, 4, 6, 1, 2, 3, 5))</code></pre>
<p>Closeness centrality is calculated using the <code>closeness_centrality()</code> function. However, in <code>networkx</code> this is normalized by multiplying the result by <span class="math inline">\(n - 1\)</span> where <span class="math inline">\(n\)</span> is the number of vertices in the graph. To obtain non-normalized closeness centrality it will be necessary to divide the output of this function by <span class="math inline">\(n - 1\)</span><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;You may wonder why &lt;span class="math inline"&gt;\(n - 1\)&lt;/span&gt;? This is simply the total number of other vertices that we are calculating the paths to. Strangely, there is no option to non-normalize in the arguments of this function as of recent versions of &lt;code&gt;networkx&lt;/code&gt;. In any case, for the purposes of comparing vertices, it doesn’t matter a great deal whether you normalize or not.&lt;/p&gt;'><sup>44</sup></a>.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb397-1"><a href="vertex-importance.html#cb397-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get non-normalized closeness centrality for Vertex 7</span></span>
<span id="cb397-2"><a href="vertex-importance.html#cb397-2" aria-hidden="true" tabindex="-1"></a>norm_closeness <span class="op">=</span> nx.closeness_centrality(g14, <span class="dv">7</span>)</span>
<span id="cb397-3"><a href="vertex-importance.html#cb397-3" aria-hidden="true" tabindex="-1"></a>norm_closeness<span class="op">/</span>(<span class="bu">len</span>(g14.nodes) <span class="op">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 0.04</code></pre>
<p>Betweenness centrality is calculated using the <code>betweenness_centrality()</code> function. Again this is normalized by default but this can be set to <code>False</code> in the arguments<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;The normalization here divides the result by the number of vertex pairs in a graph with &lt;span class="math inline"&gt;\(n-1\)&lt;/span&gt; vertices, which is &lt;span class="math inline"&gt;\((n - 1)(n - 2)\)&lt;/span&gt; for directed graphs and &lt;span class="math inline"&gt;\(\frac{(n - 1)(n - 2)}{2}\)&lt;/span&gt; for undirected graphs&lt;/p&gt;'><sup>45</sup></a>. This function calculates values for all nodes are returns them in a dict.</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb399-1"><a href="vertex-importance.html#cb399-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get non-normalized betweenness centrality for Vertex 9</span></span>
<span id="cb399-2"><a href="vertex-importance.html#cb399-2" aria-hidden="true" tabindex="-1"></a>between <span class="op">=</span> nx.betweenness_centrality(g14, normalized <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb399-3"><a href="vertex-importance.html#cb399-3" aria-hidden="true" tabindex="-1"></a>between.get(<span class="dv">9</span>)</span></code></pre></div>
<pre><code>## 46.0</code></pre>
<p>Finally, eigenvector centrality is calculated using the <code>eigenvector_centrality</code> function, with a dict returned similar to <code>betweenness_centrality()</code>.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb401-1"><a href="vertex-importance.html#cb401-1" aria-hidden="true" tabindex="-1"></a>eigen <span class="op">=</span> nx.eigenvector_centrality(g14)</span>
<span id="cb401-2"><a href="vertex-importance.html#cb401-2" aria-hidden="true" tabindex="-1"></a>eigen.get(<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## 0.5503779695532801</code></pre>
<p>Closeness, betweenness and eigenvector centrality are calculated using <em>incoming</em> edges in <code>networkx</code> digraphs. To calculate the outgoing equivalent, simply use the <code>reverse()</code> method on the digraph to make all outgoing edges incoming and vice-versa.</p>
<div class="thinkahead">
<p><strong>Playing around</strong>: <code>networkx</code> has a very wide range of centrality measures available. Visit the Centrality section of its documentation<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://networkx.org" class="uri"&gt;https://networkx.org&lt;/a&gt;&lt;/p&gt;'><sup>46</sup></a> and have a look at the options. Many of these are very specific to graph use cases in different industries and disciplines, but you can have a look at some of them, see if you can understand them and even give them a try with a data set.</p>
</div>
</div>
<div id="illustrating-centrality-in-graph-visualizations" class="section level3" number="7.2.3">
<h3>
<span class="header-section-number">7.2.3</span> Illustrating centrality in graph visualizations<a class="anchor" aria-label="anchor" href="#illustrating-centrality-in-graph-visualizations"><i class="fas fa-link"></i></a>
</h3>
<p>As we reviewed in Chapter <a href="viz-graphs.html#viz-graphs">4</a>, we will often make adjustments when visualizing graphs to illustrate certain aspects of the graph’s structure. For example, we highlight certain vertices with color or adjust the thickness of certain edges. When we want to visually illustrate the importance or influence of vertices in graphs, we will often do so using centrality measures. The two most common methods are to adjust vertex size according to centrality or to use a centrality-related color scale. We will illustrate a couple of examples using <code>ggraph</code> in R to show some of the options available.</p>
<p>For greatest efficientcy, it’s always a good idea to add centralities as vertex properties in graphs. Let’s add a few of these now in our <span class="math inline">\(G_{14}\)</span> graph.</p>
<div class="sourceCode" id="cb403"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span><span class="op">$</span><span class="va">degree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/degree.html">degree</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span><span class="op">$</span><span class="va">betweenness</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span><span class="op">$</span><span class="va">eigen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality</a></span><span class="op">(</span><span class="va">g14</span><span class="op">)</span><span class="op">$</span><span class="va">vector</span></code></pre></div>
<p>Now we can create a visualization where we map the size of vertices to the degree vertex property, as in Figure <a href="vertex-importance.html#fig:g14-degree">7.2</a>. Note the <code><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size()</a></code> function which is useful for setting a scale to suit your visualization.</p>
<div class="sourceCode" id="cb404"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">g14</span>, layout <span class="op">=</span> <span class="st">"lgl"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>size <span class="op">=</span> <span class="va">degree</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"lightblue"</span>,
                  show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size</a></span><span class="op">(</span>range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">15</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">name</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:g14-degree"></span>
<img src="_main_files/figure-html/g14-degree-1.png" alt="$G_{14}$ with vertex size scaled according to degree centrality" width="672"><p class="caption">
Figure 7.2: <span class="math inline">\(G_{14}\)</span> with vertex size scaled according to degree centrality
</p>
</div>
<p>Alternatively, Figure <a href="vertex-importance.html#fig:g14-eigen">7.3</a> shows the same graph with the vertex colors scaled according to normalized eigenvector centrality. This helps us see that the vertices to the left of Vertex 9 in <span class="math inline">\(G_{14}\)</span> do not have particularly influential connections compared to those to the right.</p>
<div class="sourceCode" id="cb405"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">g14</span>, layout <span class="op">=</span> <span class="st">"lgl"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">6</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">eigen</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_color_gradient</a></span><span class="op">(</span>low <span class="op">=</span> <span class="st">"lightblue"</span>, high <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">name</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:g14-eigen"></span>
<img src="_main_files/figure-html/g14-eigen-1.png" alt="$G_{14}$ with vertex size scaled according to normalized eigenvector centrality" width="672"><p class="caption">
Figure 7.3: <span class="math inline">\(G_{14}\)</span> with vertex size scaled according to normalized eigenvector centrality
</p>
</div>
<div class="thinkahead">
<p><strong>Playing around:</strong>. Play around with different ways of visualizing the centralities of vertices in <span class="math inline">\(G_{14}\)</span>. Try using color, size or both. And also try the different types of centrality to see if the look of the graph changes substantially between them.</p>
</div>
</div>
</div>
<div id="illustrative-7" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> Examples of uses<a class="anchor" aria-label="anchor" href="#illustrative-7"><i class="fas fa-link"></i></a>
</h2>
<p>In this section we will reprise the <code>workfrance</code> unweighted graph from the previous chapter, and use to it to illustrate some common uses for centrality measures. First we will look at how to find network-wide and department level ‘superconnectors,’ then we will look at how to find potential socially-influential actors in a network. Let’s load up the <code>workfrance</code> graph again.</p>
<div class="sourceCode" id="cb406"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>

<span class="co"># download workfrance data sets</span>
<span class="va">workfrance_edges</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"https://ona-book.org/data/workfrance_edgelist.csv"</span><span class="op">)</span>
<span class="va">workfrance_vertices</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"https://ona-book.org/data/workfrance_vertices.csv"</span><span class="op">)</span>

<span class="co"># create graph</span>
<span class="va">workfrance</span> <span class="op">&lt;-</span> <span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/graph_from_data_frame.html">graph_from_data_frame</a></span><span class="op">(</span>
    d <span class="op">=</span> <span class="va">workfrance_edges</span>,
    vertices <span class="op">=</span> <span class="va">workfrance_vertices</span>,
    directed <span class="op">=</span> <span class="cn">FALSE</span>
<span class="op">)</span></code></pre></div>
<div id="finding-superconnectors" class="section level3" number="7.3.1">
<h3>
<span class="header-section-number">7.3.1</span> Finding ‘superconnectors’<a class="anchor" aria-label="anchor" href="#finding-superconnectors"><i class="fas fa-link"></i></a>
</h3>
<p>Individuals with high betweenness centrality in people networks could be regarded as ‘superconnectors.’ Superconnectors can play very valuable roles in the social integration of new entrants to the network, and can also present greater risk of connective disruption if they leave the network. Imagine a new hire is about to join the DMI department in our <code>workfrance</code> network. We want to assign two ‘buddies’ to this individual to help them socially integrate into the workplace more effectively. Given that it is important for the individual to assimilate into their own department and into the workplace as a whole, we want to select the best two current employees to assist with both goals. Let’s start with the DMI department first.</p>
<p>In order to study the DMI department as a self-contained network, we will create an induced subgraph which contains only those in that department and the connections between them, and visualize this network, labeling the employee IDs, as in <a href="vertex-importance.html#fig:dmi-workfrance">7.4</a>.</p>
<div class="sourceCode" id="cb407"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create DMI subgraph</span>
<span class="va">DMI_vertices</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">dept</span> <span class="op">==</span> <span class="st">"DMI"</span><span class="op">]</span>
<span class="va">DMI_graph</span> <span class="op">&lt;-</span> <span class="fu">igraph</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/subgraph.html">induced.subgraph</a></span><span class="op">(</span><span class="va">workfrance</span>, vids <span class="op">=</span> <span class="va">DMI_vertices</span><span class="op">)</span>

<span class="co"># visualize</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"lightblue"</span>, size <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">name</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:dmi-workfrance"></span>
<img src="_main_files/figure-html/dmi-workfrance-1.png" alt="The induced subgraph of the DMI department in `workfrance`" width="672"><p class="caption">
Figure 7.4: The induced subgraph of the DMI department in <code>workfrance</code>
</p>
</div>
<p>Now we are interested in those who have the strongest role in connecting others in this network. Let’s find the top three individuals in terms of betweenness centrality.</p>
<div class="sourceCode" id="cb408"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get IDs of top 3 betweenness centralities</span>
<span class="va">ranked_betweenness_DMI</span> <span class="op">&lt;-</span> <span class="va">DMI_graph</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> 

<span class="op">(</span><span class="va">top3_DMI</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ranked_betweenness_DMI</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "156" "74"  "884"</code></pre>
<p>These are the IDs of the top three superconnectors in the DMI department. Now we can visualize the graph again, but let’s adjust vertex size by betweenness and color the top three superconnectors, as in Figure <a href="vertex-importance.html#fig:dmi-superconnectors">7.5</a>.</p>
<div class="sourceCode" id="cb410"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># add betweenness vertex property</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span><span class="op">$</span><span class="va">betweenness</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span>

<span class="co"># add top three superconnectors property</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span><span class="op">$</span><span class="va">top3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span><span class="op">$</span><span class="va">name</span> <span class="op">%in%</span> <span class="va">top3_DMI</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>

<span class="co"># visualize</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">DMI_graph</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">top3</span><span class="op">)</span>, size <span class="op">=</span> <span class="va">betweenness</span><span class="op">)</span>,
                  show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"lightblue"</span>, <span class="st">"pink"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">name</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:dmi-superconnectors"></span>
<img src="_main_files/figure-html/dmi-superconnectors-1.png" alt="DMI subgraph with the top three superconnectors identified" width="672"><p class="caption">
Figure 7.5: DMI subgraph with the top three superconnectors identified
</p>
</div>
<p>In a similar way we can find the superconnectors of the overall <code>workfrance</code> network.</p>
<div class="sourceCode" id="cb411"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get IDs of top 3 betweenness centralities</span>
<span class="va">ranked_betweenness_workfrance</span> <span class="op">&lt;-</span> <span class="va">workfrance</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> 

<span class="co">#get top 3</span>
<span class="op">(</span><span class="va">top3_workfrance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ranked_betweenness_workfrance</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "603" "99"  "322"</code></pre>
<p>In Figure <a href="vertex-importance.html#fig:workfrance-superconnectors">7.6</a>, we create a graph of the <code>workfrance</code> network with nodes scaled by betweenness centrality. We color by department so we can easily see which departments our superconnectors are in.</p>
<div class="sourceCode" id="cb413"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># add betweenness property</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">betweenness</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/betweenness.html">betweenness</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span>

<span class="co"># label only if a top3 superconnector</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">btwn_label</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">name</span> <span class="op">%in%</span> <span class="va">top3_workfrance</span>,
                              <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">name</span>, <span class="st">""</span><span class="op">)</span>

<span class="co"># visualize</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">dept</span>, size <span class="op">=</span> <span class="va">betweenness</span><span class="op">)</span>,
                  show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">btwn_label</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:workfrance-superconnectors"></span>
<img src="_main_files/figure-html/workfrance-superconnectors-1.png" alt="`workfrance` graph with the top three superconnectors identified" width="672"><p class="caption">
Figure 7.6: <code>workfrance</code> graph with the top three superconnectors identified
</p>
</div>
<p>We can see upon examination that our top three organization-wide superconnectors are all in different departments. Putting all this together, it would seem that a good choice of buddies for the new hire would be employee 156 for departmental integration and employee 603 for office-wide integration, although any combination of the six individuals identified through this analysis would probably be decent choices.</p>
</div>
<div id="identifying-influential-employees" class="section level3" number="7.3.2">
<h3>
<span class="header-section-number">7.3.2</span> Identifying influential employees<a class="anchor" aria-label="anchor" href="#identifying-influential-employees"><i class="fas fa-link"></i></a>
</h3>
<p>Influential actors in a network can be very useful to identify. In organizational contexts, working with more influential employees can make a difference to how certain initiatives or changes can be perceived by other employees. Influential employees can also be useful in efficiently tapping into prevalent opinions across the entire employee population. Imagine that we want to identify individuals from across the organization to participate in important workshops to problem solve some critical operational initiatives. These initiatives will affect employees at both an overall and a department level, therefore it would be ideal to have individuals who are influential within each department as well as across the entire organization.</p>
<p>Again, let’s look at a single department - the DMI department as an example. Because we are interested in overall influence, this could mean we are equally interested in employees with a lot of connections or employees who are ‘stealthily’ infuential in being connected to a smaller number of other highly connected employees. The best measure for this is eigenvector centrality.</p>
<p>First we identify the top three most influential individuals in the DMI department as measured by eigenvector centrality by working on the DMI subgraph.</p>
<div class="sourceCode" id="cb414"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># working with lists so use purrr package</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://purrr.tidyverse.org">purrr</a></span><span class="op">)</span>

<span class="co"># get IDs of top 3 eigen centrality</span>
<span class="va">ranked_eigen_DMI</span> <span class="op">&lt;-</span> <span class="va">DMI_graph</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality</a></span><span class="op">(</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"vector"</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="co">#get top 3</span>
<span class="op">(</span><span class="va">top3_DMI_eigen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ranked_eigen_DMI</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<pre><code>## [1] "884" "156" "642"</code></pre>
<p>We see two employee IDs in common with our top 3 superconnectors. We can also identify the top 3 most influential individuals across the <code>workfrance</code> graph according to their eigenvector centrality.</p>
<div class="sourceCode" id="cb416"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get IDs of top 3 eigen centrality</span>
<span class="va">ranked_eigen_workfrance</span> <span class="op">&lt;-</span> <span class="va">workfrance</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality</a></span><span class="op">(</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"vector"</span><span class="op">)</span> |&gt; 
  <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span>decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="co">#get top 3</span>
<span class="op">(</span><span class="va">top3_workfrance_eigen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ranked_eigen_workfrance</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<pre><code>## [1] "603" "649" "147"</code></pre>
<p>We see one individual in common with our top 3 superconnectors. Let’s visualize this network so we can identify the department mix of our top 3 most influential individuals, as in Figure <a href="vertex-importance.html#fig:eigen-workfrance">7.7</a>.</p>
<div class="sourceCode" id="cb418"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># add betweenness property</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">eigen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/eigen_centrality.html">eigen_centrality</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">vector</span>

<span class="co"># label only if a top3 superconnector</span>
<span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">eigen_label</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">name</span> <span class="op">%in%</span> <span class="va">top3_workfrance_eigen</span>,
                              <span class="fu"><a href="https://rdrr.io/pkg/igraph/man/V.html">V</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span><span class="op">$</span><span class="va">name</span>, <span class="st">""</span><span class="op">)</span>

<span class="co"># visualize</span>
<span class="fu"><a href="https://ggraph.data-imaginist.com/reference/ggraph.html">ggraph</a></span><span class="op">(</span><span class="va">workfrance</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_edge_link.html">geom_edge_link</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_point.html">geom_node_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">dept</span>, size <span class="op">=</span> <span class="va">eigen</span><span class="op">)</span>,
                  show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggraph.data-imaginist.com/reference/geom_node_text.html">geom_node_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">eigen_label</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:eigen-workfrance"></span>
<img src="_main_files/figure-html/eigen-workfrance-1.png" alt="`workfrance` graph with the top three most influential vertices  identified" width="672"><p class="caption">
Figure 7.7: <code>workfrance</code> graph with the top three most influential vertices identified
</p>
</div>
<p>This time we see that our three most influential individuals are all in the same department, suggesting that this department may be a strategically important one to involve in any planned change initiatives.</p>
</div>
</div>
<div id="learning-exercises-5" class="section level2" number="7.4">
<h2>
<span class="header-section-number">7.4</span> Learning exercises<a class="anchor" aria-label="anchor" href="#learning-exercises-5"><i class="fas fa-link"></i></a>
</h2>
<div id="discussion-questions-5" class="section level3" number="7.4.1">
<h3>
<span class="header-section-number">7.4.1</span> Discussion questions<a class="anchor" aria-label="anchor" href="#discussion-questions-5"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>Describe the general concept of vertex centrality in networks and why it is important.</li>
<li>Define the degree centrality of a vertex <span class="math inline">\(v\)</span> in an undirected graph <span class="math inline">\(G\)</span> in at least two different ways. How would you interpret the degree centrality of <span class="math inline">\(v\)</span> in an organizational network? Manually calculate the degree centrality of vertices 9, 10 and 11 in <span class="math inline">\(G_{14}\)</span>.</li>
<li>Draw the 2nd-order ego network of Vertex 8 in <span class="math inline">\(G_{14}\)</span>. What is the 2nd-order ego size of Vertex 8?</li>
<li>Define closeness centrality and describe how it can be interpreted. Manually calculate the closeness centrality of Vertex 10 in <span class="math inline">\(G_{14}\)</span> (feel free to express your answer as a fraction).</li>
<li>Define betweenness centrality and describe how it can be interpreted. Manually calculate the betweenness centrality of Vertex 4 in <span class="math inline">\(G_{14}\)</span>.</li>
<li>Describe how you would interpret the eigenvector centrality of a vertex in an undirected graph <span class="math inline">\(G\)</span>.<br>
</li>
<li>For each of the four main centrality measures — degree, closeness, betweenness and eigenvector — write down some potential benefits from knowing which individuals rank highest in a people network?</li>
<li>When visualizing graphs, name some ways to illustrate vertex centrality.</li>
<li>Why might some centrality functions in R or Python not actually output the raw centrality measure? Give an example of this. Do you think it matters? What would you do to correct it if you need to?<br>
</li>
<li>Describe the some additional considerations in the calculation of vertex centrality in the case of directed graphs and in the case of weighted graphs.</li>
</ol>
</div>
<div id="data-exercises-5" class="section level3" number="7.4.2">
<h3>
<span class="header-section-number">7.4.2</span> Data exercises<a class="anchor" aria-label="anchor" href="#data-exercises-5"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>Use an appropriate function to calculate the degree centrality of vertices 9, 10 and 11 in <span class="math inline">\(G_{14}\)</span> and verify that the output matches your manual calculations from the earlier questions.</li>
<li>Create and visualize the 2nd-order ego network of Vertex 8 in <span class="math inline">\(G_{14}\)</span>.</li>
<li>Use an appropriate function to calculate the closeness centrality of Vertex 10 in <span class="math inline">\(G_{14}\)</span> and verify that it agrees with your manual calculation from the earlier questions.</li>
<li>Use an appropriate function to calculate the betweenness centrality of Vertex 4 in <span class="math inline">\(G_{14}\)</span> and verify that it agrees with your manual calculation from the earlier questions.</li>
<li>Find the mean eigenvector centrality of all vertices in <span class="math inline">\(G_{14}\)</span>. Do this twice, raw and normalized.</li>
<li>Visualize <span class="math inline">\(G_{14}\)</span> with the size of the vertices scaled to their eigenvector centrality and the color scaled to their closeness centrality.</li>
</ol>
<p>For questions 6 to 10, create an undirected graph from the Facebook friendships in the <code>schoolfriends_edgelist</code> and <code>schoolfriends_vertices</code> datasets in the <code>onadata</code> package or downloaded from the internet<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="https://ona-book.org/data/schoolfriends_edgelist.csv" class="uri"&gt;https://ona-book.org/data/schoolfriends_edgelist.csv&lt;/a&gt; and &lt;a href="https://ona-book.org/data/schoolfriends_vertices.csv" class="uri"&gt;https://ona-book.org/data/schoolfriends_vertices.csv&lt;/a&gt;&lt;/p&gt;'><sup>47</sup></a>. Recall from the exercises in Chapter <a href="viz-graphs.html#viz-graphs">4</a> that this data contains information on friendships between high school students in France. Make sure not to include the reported friendships in this graph. There are a lot of isolates in this graph because it only represents ‘known’ Facebook friendships, and you should remove isolates before proceeding<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;One easy way to identify isolates in a graph object &lt;code&gt;G&lt;/code&gt; in R to identify them using &lt;code&gt;isolates &amp;lt;- which(degree(G) == 0)&lt;/code&gt;, and then remove them using &lt;code&gt;G_new &amp;lt;- remove.vertices(G, isolates)&lt;/code&gt;.&lt;/p&gt;"><sup>48</sup></a>.</p>
<ol start="6" style="list-style-type: decimal">
<li>Identify the top three individuals with the most Facebook connections.</li>
<li>Determine 1st-degree and 2nd-degree ego sizes of the individual with the most Facebook connections. What proportion of the total population is included in these ego networks?</li>
<li>Plot the distribution of the degree centrality of all vertices using a histogram or density plot.<br>
</li>
<li>Identify which individuals have the maximum closeness centrality, betweenness centrality and eigenvector centrality in the graph. Visualize the network color coded by class and identify where these individuals are. What do you notice?</li>
<li>If you were the leader of this high school and were deciding class placements for next year, how might this information be useful to you?</li>
</ol>
<p><strong>Extension:</strong>. For these questions, create a <em>directed</em> graph from the <em>reported</em> friendships in the same data set, and remove the isolates as before.</p>
<ol start="11" style="list-style-type: decimal">
<li>Identify the individuals with the maximum in-degree centrality and the maximum out-degree centrality in this network? How would you describe these two individuals in the friendship dynamics of the high school? Do you see anything in common with the Facebook friendships?</li>
<li>Calculate the hub scores and authority scores of the vertices. How would you interpret these?</li>
<li>Determine the 1st degree ego network of the individual with the highest authority score. Visualize this as a <em>directed</em> network with vertices color coded by class. Do the same for the individual with the highest hub score. Can you use these visualizations to describe the these individuals have high authority/hub scores?</li>
</ol>
</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="paths-distance.html"><span class="header-section-number">6</span> Paths and Distance</a></div>
<div class="next"><a href="community.html"><span class="header-section-number">8</span> Components, Communities and Cliques</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#vertex-importance"><span class="header-section-number">7</span> Vertex Importance and Centrality</a></li>
<li>
<a class="nav-link" href="#vertex-centrality-measures-in-graphs"><span class="header-section-number">7.1</span> Vertex centrality measures in graphs</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#degree-centrality"><span class="header-section-number">7.1.1</span> Degree centrality</a></li>
<li><a class="nav-link" href="#closeness-centrality"><span class="header-section-number">7.1.2</span> Closeness centrality</a></li>
<li><a class="nav-link" href="#betweenness-centrality"><span class="header-section-number">7.1.3</span> Betweenness centrality</a></li>
<li><a class="nav-link" href="#eigenvector-centrality"><span class="header-section-number">7.1.4</span> Eigenvector centrality</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#calculating-and-illustrating-vertex-centrality"><span class="header-section-number">7.2</span> Calculating and illustrating vertex centrality</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#calculating-in-r-1"><span class="header-section-number">7.2.1</span> Calculating in R</a></li>
<li><a class="nav-link" href="#calculating-in-python-1"><span class="header-section-number">7.2.2</span> Calculating in Python</a></li>
<li><a class="nav-link" href="#illustrating-centrality-in-graph-visualizations"><span class="header-section-number">7.2.3</span> Illustrating centrality in graph visualizations</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#illustrative-7"><span class="header-section-number">7.3</span> Examples of uses</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#finding-superconnectors"><span class="header-section-number">7.3.1</span> Finding ‘superconnectors’</a></li>
<li><a class="nav-link" href="#identifying-influential-employees"><span class="header-section-number">7.3.2</span> Identifying influential employees</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#learning-exercises-5"><span class="header-section-number">7.4</span> Learning exercises</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#discussion-questions-5"><span class="header-section-number">7.4.1</span> Discussion questions</a></li>
<li><a class="nav-link" href="#data-exercises-5"><span class="header-section-number">7.4.2</span> Data exercises</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/keithmcnulty/ona_book/blob/master/r/07-vertex_importance.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/keithmcnulty/ona_book/edit/master/r/07-vertex_importance.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Handbook of Graphs and Networks in People Analytics</strong>: With Examples in R and Python" was written by Keith McNulty. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
