# Foreword by Professor Jeff Polzer {-}

We all understand that when it comes to getting things done in organizations, “who you know” matters. This truism only scratches the surface, though, of how deeply our social networks affect everything we do. They shape our day-to-day opportunities through every meeting, email, and serendipitous encounter, just as each interaction in turn alters our networks. We strengthen some relationships, develop new ones, and let others languish. We spend lots of time and attention focusing on our immediate relationships, and for good reason; they are a source of joy and psychological fulfillment, while helping us do our jobs and achieve our goals.

If we give most of our attention to our direct relationships, however, we miss an important part of the social structure in which we are embedded. After all, it's not just who we know, but who our friends and colleagues know that helps us succeed. These more distant, indirect connections are hard to discern, and our accuracy diminishes when we try to evaluate these indirect ties or make sense of how they fit into a larger picture. Though hidden from our direct line of sight, this social structure has a powerful influence on what we, and our organizations, can achieve. 

This is where Keith McNulty’s new book on network analysis comes into play. He draws on a rich tradition of social science to distill what we know about networks and clearly explain how to analyze and apply network data to organizational challenges. Network researchers have identified powerful patterns that are easily overlooked from any one person's vantage point, from in-depth studies of relationships among small groups of employees, to intricate analyses of teams embedded in organizational networks, to cross-firm investigations of interlocked boards of directors, among many others. The beauty of network analysis is that it allows seemingly simple dyadic connections between individuals to be knit together into an entire social structure. This approach allows us to zoom in or out to answer questions at different levels of analysis, whether about the centrality of a specific individual or the centralized structure of an entire organization. 

The time is ripe for organizations to embrace network analyses to understand how connections among employees are helping or hurting their ability to achieve their goals. As companies have come to understand the value of using network techniques in their core business, such as Google using links between websites to organize internet searches, or LinkedIn using ties between platform users to guide job searches, they have started to experiment with using network concepts and methods to address their workforce challenges. The availability of new digital sources of data and ever-growing computational power, coupled with the well-documented rigor of network methods, hold great promise for understanding how employee networks function. 

Some companies at the forefront of this field incorporated network analyses into their toolkits years ago, in many cases importing and adapting methods from academic research via their newly minted people analytics teams. Other organizations, however, have not yet considered this approach or have encountered obstacles along the way. While most managers, for example, intuitively understand the basic importance of "networking," some still view rigorous network analysis as an esoteric subject. Others may struggle to decide what sources of employee data to use—whether from digital communication platforms, surveys, or HR information systems—or how to gather and prepare the data for this type of analysis without violating employee privacy and trust. As a result of these challenges, the gap between what is possible and what is currently in practice remains wide, in part because those poised to do this work may not appreciate the extent to which network methods are adaptable and versatile.

This book aims to bridge this gap, laying out the foundational building blocks of networks in terms of the concepts, terminology, data, analyses, and code, complete with hands-on examples of real use cases. It is exciting and inspiring to see the way McNulty explains network methods, as he unpacks the distinct elements and analytic steps to make them transparent. This makes it easier for readers to see how these elements fit together and apply to organizational challenges, sparking new ideas for innovative solutions. By demystifying this topic, McNulty empowers people to find their own solutions and engage in more productive conversations, regardless of who is writing the actual code or running the analyses. This book can help to democratize network analysis and improve the level of data fluency in organizations more generally. Considering the benefits of understanding network analysis, it is easy to see why top business schools now include it in their curriculum, whether in a course on People Analytics or in other domains. 

With a clearer understanding of network methods in hand, the potential applications for this approach should excite not only those in human resources and people analytics, but also managers who are trying to help employees work together in a more productive and sustainable way that improves both individual and collective welfare. Virtually every organization is trying to juggle the demand by some employees to work remotely, while others anxiously wait to return to the office, creating the need to design hybrid arrangements that satisfy everyone. Communication and collaboration networks are at the very heart of these questions, whether the goal is to execute current projects, spur innovation, or improve employee well-being. Companies are now using network analyses to help with challenges that include socializing new hires, cultivating an environment of inclusion and belonging, preventing collaboration overload and burnout, and planning office utilization. Beyond these types of organizational concerns, scientists across disciplines are using these tools to tackle the world’s most pressing problems, from mapping the spread of infectious disease to understanding the social conduits of political polarization. All of these issues, and many more, are amenable to network approaches. This valuable book can help you examine these challenges from new angles and design fresh approaches to address them. 

`r if (knitr::is_html_output()) {"[Jeff Polzer](https://www.linkedin.com/in/jeff-polzer-17391612/)"} else {"Jeff Polzer"}` \
December 2021

***Jeffrey T. Polzer** is the UPS Foundation Professor of Human Resource Management in the Organizational Behavior Unit at Harvard Business School. He studies how people collaborate in teams and across organizational networks to accomplish their individual and collective goals. He has ongoing projects in collaboration with a number of organizations, often working with members of their people analytics groups on problems of mutual interest. He has taught a variety of courses in the MBA, Executive, and Doctoral Programs at HBS, and published his research in numerous top management and psychology journals.*




